version: "2.4"

services:
  smtp:
    image: reachfive/fake-smtp-server
    networks:
      - backend
    ports:
      - 1080:1080

  mailify:
    # if you want to use the last version
    # image: trinhminhtriet/mailify:canary
    # if you want to build it locally
    build: .
    environment:
      LOG: debug
      SMTP__HOSTNAME: smtp
      SMTP__PORT: 1025
      TEMPLATE__TYPE: local
      TEMPLATE__PATH: /template
    networks:
      - backend
    ports:
      - 3010:3000
    volumes:
      - ./template:/template:ro

networks:
  backend: {}
